#### Clasifica_textos_pgd

In [171]:
# Limpiamos el entorno de trabajo
rm(list = ls())

In [ ]:
#Paqueterías y librerías
if(!require('pacman')) install.packages('pacman')
pacman::p_load(googlesheets4, googledrive, dplyr, tidyr, stringr, stringi, digest, purrr, janitor, readr, writexl)

In [173]:
# ── 2. CONFIGURACIÓN (sin autenticación) ──────────────────────
googlesheets4::gs4_deauth()

folder_id <- "1T26Htx7qrty3UwMkBUT9mfWg6azOylJK"
sheet_key <- "1jGSoc-KZK3Q_p5c9UbcZNpAyBW3rVyJI3ERuszdkFe4"

In [174]:
talleres_raw <- googlesheets4::read_sheet(sheet_key, sheet = 1,
                                      col_types = "c") %>%
  janitor::clean_names() %>%
  select(1:19)

✔ Reading from demo.

✔ Range ''Hoja 1''.

New names:
• `¿Se llevó a cabo el taller?` -> `¿Se llevó a cabo el taller?...7`
• `¿Se llevó a cabo el taller?` -> `¿Se llevó a cabo el taller?...20`

In [175]:
cat("Total de registros:", nrow(talleres_raw), "\n")
head(talleres_raw, 5)

Total de registros: 427

  marca_temporal      direccion_de_correo_electronico
1 24/11/2025 12:01:11 paulinamorales3414@gmail.com
2 25/11/2025 18:02:00 paulinamorales3414@gmail.com
3 25/11/2025 18:38:59 paulinamorales3414@gmail.com
4 25/11/2025 20:04:04 paulinamorales3414@gmail.com
5 25/11/2025 20:22:02 paulinamorales3414@gmail.com
  lugar_programado_del_evento fecha_programada_del_evento
1 VIVERO NEZAHUALCÓYOTL       13/11/2025
2 100 METROS                  11/11/2025
3 MARTHA PÉREZ BEJARANO       12/11/2025
4 ESCUADRÓN 201               12/11/2025
5 SAN MIGUEL AMANTLA          15/11/2025
  hora_programada_de_inicio_del_evento
1 3:00:00 p.m.
2 11:00:00 a.m.
3 10:00:00 a.m.
4 3:00:00 p.m.
5 1:00:00 p.m.
  tipo_de_evento                                 se_llevo_a_cabo_el_taller_7
1 1a sesión: "De los problemas a las propuestas" Sí
2 1a sesión: "De los problemas a las propuestas" Sí
3 1a sesión: "De los problemas a las propuestas" Sí
4 1a sesión: "De los problemas a las propuestas" Sí
5 1a sesión: "De los problemas a las propuestas" Sí
  medio_ambiente_agua_y_riesgos_problematicas
1 Escasez del agua, el agua está contaminada; hay residuos tóxicos, basura; Hay pérdida de áreas verdes; hay colapso en el drenaje; existe sobrepoblación de animales callejeros; Hay contaminación en canales, bosques y zonas de conservación; urbanización (descentralización); Contaminación vehicular; Discriminación por preferencia sexual; Acoso sexual; Racismo; Clasismo; Homofobia; No hay igualdad y equidad; Agresiones físicas y psicológicas; No hay calidad en el agua; Hay abandono del campo; Las chinampas se están perdiendo; se usan motores que dañan a las chinampas; No es equitativa la cobertura de programas de capacitación de agua
2 Parques sucios, inseguros; Calles con banquetas destruidas; Sistema de drenaje obstruido; La gente no va a los lugares de reciclaje; Escasez de agua; Aguas sustentables; Basuras; Bordos de los ríos con basura, fauna nociva y vegetación extensa que impide el paso peatonal; Mal uso del agua; Mujeres con discapacidad no pueden transitar libremente; Niñas y niños no pueden usar los parques; Inundaciones; Mujeres con problemas sin agua para las actividades del hogar; Afecta a la salud de la población; Mujeres mayormente vulnerables a asaltos o abuso sexual (seguridad)
3 Fugas de agua y falta de agua; No hay espacios verdes, Hay animales callejeros; Hay basura y plagas; Hay contaminación auditiva, ambiental y visual; Las áreas verdes se encuentran desatendidas, dañadas, con plagas y fauna nociva
4 Desigualdad en el abastecimiento de agua; Fugas de agua; Riesgo / fracturas áreas del Metro, Puentes Peatonales y escalinatas por sismos; Puente vehicular con fracturas; Inundación en el Metro (dentro); No sirven los alertas sísmicas
5 Desabasto de agua por gentrificación; Yo recuerdo desde niña en San Miguel Amantla siempre nos faltaba el agua; Agua para todos y hay mucha inseguridad; No más viviendas realizadas por privados; Abasto de Agua igualitario, ya que en zonas cercanas tienen agua todo el día; Problemática de la basura en la vía pública, principalmente por vivienda; Los cruces son inseguros para las mujeres; Los horarios de camiones de basura son limitados; No hay responsabilidad en colonias que están entre delimitaciones territoriales de alcaldías, están inseguras  porque está desprotegido por falta de mantenimiento; Hay personas que recolectan basura clandestinos que ocasionan enfermedades; Fiestas patronales o de pueblo; Recicladora ocasiona malestar por material tóxico, riesgo a la población y fauna nociva
  medio_ambiente_agua_y_riesgos_posibles_soluciones
1 Reutilizar Agua; Sustentabilidad del Agua; Reparación de fugas de Agua; Manejo y control de residuos; Botes, camiones y separación; Recuperación de Áreas Verdes; No tirar basura, Mantenimiento; Adopción, Esterilización y Concientizar a la población; Recuperación, limpieza y Normas; Planeación territorial; Transportes más ecológicos; Incentivar uso de bicicleta; Regulación a fábricas y empresas; Respeto, Educación e Inclusión; Leyes Justas; Ayuda psicológica; Fomentar Empatía; Equidad; Que sea equitativa la distribución del agua y su disponibilidad; que haya convenios para que no se abandone el campo; Dar prioridad a zonas cerriles para programas de agua
2 Limpieza; Alumbrado público; Alcaldías respondan solicitudes; Desazolve; Invitar a las personas a que asistan; Multas si contaminan; Brindar servicio de agua a las poblaciones con este problema persistente; Captación de agua potable; Reciclables y uso de basura; Multas para personas que dejan heces de perros (de casa)
3 Camiones que se lleven residuos grandes como (colchones, salas, etc.); Atención inmediata; Limpieza y reforestación; Esterilizaciones y fomentar empatía a los animales; Generar conciencia y buenos hábitos; Espacios asignados para eventos masivos; Retirar publicidad, que el espacio público esté limpio y en buenas condiciones; Usar bicicleta y fomentar su uso; Fomentar el uso del transporte público; Creación de empresas comunitarias en actividades de beneficio ecológico; Creación de más áreas; Difusión de técnicas, por ejemplo, la hidroponía; Tener más conciencia de cómo separamos la basura; Más difusión de cómo tratar los problemas de basura; Más contenedores y servicio nocturno de recolección de basura
4 El agua tiene que ser para todos / por igual; No se desperdicie el agua; Atender fugas de agua; Distribución equitativa; Mantenimiento de las áreas responsables; Revisión, mantenimiento y seguimiento para que no haya riesgos; Adaptar la infraestructura
5 Captación de agua pluvial (mega cisterna en un lugar a asignar a nuevos edificios. Lugar estratégico; otro pozo de agua en buenas condiciones, con buen mantenimiento y que realmente llegue a nuestra colonia, que no sea privilegio para unos cuantos; Más policías, más alumbramiento; No dar más contratos a inmobiliarias privadas; Hacer un estudio y análisis de la zona para abastecer por igual y sin discriminación por zona, lugar o pozos; Concientizar a la población de apoyar con el barrido del frente de su vivienda; Apoyar con carteles, campañas de limpia; Concientizar el que recojan las heces de sus mascotas (mejor planificación de residuos); Seguridad general, hay mucha inseguridad; Senderos seguros, con alumbrado y seguridad; respuestas en 15 días; Botón de pánico funcionales; Cámaras c5 que funcionen; Que se extienda el servicio con una buena logística por colonias; Vigilancia extrema y cámaras en buen funcionamiento; Concientizar a la población, extender la ruta y horarios de basura;  vigilancia por parte de las autoridades; Vigilancia para evitar que se tire basura; Mejoras para desarrollos de parques; La recicladora no debe estar en la Ciudad de México sino fuera
  medio_ambiente_agua_y_riesgos_opiniones
1 NA
2 NA
3 NA
4 NA
5 NA
  espacio_publico_vivienda_movilidad_y_democracia_problematicas
1 Mobiliario de parques en riesgos; Hay vandalismo; Límites territoriales entre alcaldías no es claro; Vivienda únicamente para derechohabientes; No hay cultura de ciclovías; Transporte público en malas condiciones; No se reconoce la vivienda en zonas cerriles; Espacio público sin mantenimiento, drogadicción, alumbrado, seguridad, abandono, sin agua, fauna nociva, lo que se construye es privado, baños públicos sin infraestructura para discapacitados; La vivienda tiene altos costos y escasez de vivienda, gentrificación, uso de suelo, construcciones irregulares e inseguras, sin créditos accesibles; En movilidad el transporte público está saturado; sin vías de acceso, alto tránsito vehicular, falta cultura vial, no hay seguimiento al reglamento de tránsito, no hay infraestructura para discapacitados; violencia de género, acoso, violaciones, violencia psicológica, discrminación y exclusión
2 Cámaras de seguridad sin funcionar; Falta de regulación en bicis eléctricas; Tirar basura (vecinos en espacio público); Tiempos largos de traslado en el transporte público; Heces de perros; Falta de respeto por parte de los automóviles a ciclistas; Franeleros, apropiación del espacio; Apropiación del espacio público (cierre de calles); Intimidación para el uso de espacio público; Rentas elevadas e injustificadas; Muchos automóviles en un pequeño espacio; No hay bicis en todas las zonas; No hay espacio para vivienda; Esparcimiento en cerros con o sin permiso; Población de bajos recursos sin cultura; Regulación en el uso de motocicletas; Irregularidades en bicitaxis, son majaderos; Baches en calles y avenidas; Falta de respeto a las mujeres y a la tercera edad por bicitaxeros; Considerar más a la mujer en espacios públicos; Las mujeres se ven obligadas a laborar, sufren traslados largos; Falta de empatía de las mujeres en el transporte público o adultos mayores o discapacitados; Las rentas altas afectan a las madres solteras
3 Espacios públicos mal aprovechados; Vivienda, costos excesivos que no son acorde al salario mínimo; Predios irregulares; Ineficiente e insuficiente transporte público, RTP y Cablebús; Recuperación de espacios de recreación; Recuperación de vialidades; Acoso en espacios públicos; Falta de transporte para mujeres; No hay senderos seguros ni cruces para adultos mayores; Hay vecinos ruidosos y agresivos; Banquetas invadidas principalmente por comercios tanto establecidos o fijos como ambulantes y carros; Hay desplazamiento de la comunidad por la carencia de la vivienda, precios elevados; No hay seguridad para escuelas
4 Flota de motos elevada y no respetan los conductores; carencia de vivienda digna para adultos mayores, sin espacios adecuados para su movilidad; es difícil tener acceso a la vivienda en cuanto a compra; falta de mantenimiento del espacio público: parques áreas verdes, etc.; hay mayor presencia de vivienda privada; hay personas indigentes que alteran el bienestar de la población, causan inseguridad, acoso y provocan que no se puede usar el espacio público; falta de espacios rampas accesibilidad universal, problema para personas con discapacidad; Género: acoso en todo el espacio público; Los trámites son burocráticos largos y no sean claros; no hay difusión de eventos públicos como la consulta del peje de; claridad de donde comunicarse ante problemas; difusión de medios de contacto para seguimiento de trámites; los pueblos y barrios originarios tienen venta de cohetes sin regularizar y su uso ocasionan mucho ruido en sus fiestas patronales
5 Obstrucción de rampas y autos estacionados en esquinas dificultan el tránsito con silla de ruedas y carriolas, no permiten el cruce de calle de forma segura; Falta señalética (calles, avenidas y código postal) se encuentran deterioradas y necesitan mejoramiento; Hace falta banquetas porque es inseguro para la gente que e desplaza por la calle; No hay respeto al estacionar autos, los ponen donde quieren sin respetar a los vecinos, lugares no autorizados y eso ha ocasionado conflictos vecinales; No hay desarrollo de vivienda bien planeada ni consultada; Se obstruye el paso por microbuses; Faltan espacios para niños, los que están, se encuentran en malas condiciones; No hay repuesta a solicitudes; No hay infraestructura para los problemas que genera la lluvia
  espacio_publico_vivienda_movilidad_y_democracia_posibles_soluciones
1 Rondines de patrullaje; Que verdaderamente se aplique la ley; Que los vecinos reporten anomalías; Que las alcaldías trabajen y se organicen para su delimitación y atención; Tienen que haber programa de vivienda para todos con cobertura universal; Debe haber más ciclovías; Debe haber sanciones e infracciones; Debe haber mantenimiento a las instalaciones, a las ciclovías y todo lo que se pone; Mejora al transporte público; Se deben incorporar programas en las zonas cerriles; jornadas con la alcaldía y vecinos de manera periódica, instalar luminarias, cámaras, patrullaje, botones de pánico, abastecimiento de agua; Construcción de vivienda con bajo costo para la población a cargo del gobierno; Crédito de vivienda; Establecer límite de uso de vivienda para fines turísticos; Más transporte público, mantenimiento, fomentar el acto compartido, talleres de cultura vial, adecuación de infraestructura para discapacitados, transporte alternativo; cultura, políticas inclusivas; Más programas para jefas de hogar, subsidios y requisitos flexibles y claros
2 Dar seguimiento a su funcionalidad; Regular las bicis eléctricas y patinetas; Vigilancia, cámaras por autoridades; Más rutas del camión; Implementar jornadas híbridas (home office); Multas; Diseño de ciclovías adecuadas y seguras; Ciclistas respeten reglamento de seguridad; Ejercer el derecho de libre tránsito del espacio público; Guardia Nacional; Congelar las rentas; Doble no circula más drástico (menos autos circulantes); Mejora en el servicio de transporte público; Bicis en todas las zonas que no tienen infraestructura; Reubicación en unidades habitacionales dignas y bien localizadas; Respetar el reglamento de tránsito; Regulación en el uso de motocicletas; Limpieza en parques; Iluminación en todos los espacios y podas; Pavimentación bien planeada; Regularicen los precios de bicitaxi; Tener conciencia de los parques, nos apoyen en lugares de entretenimiento familiar, personal capacitado; La iluminación tanto en comunidades y donde hay transportes; Espacios para infantes de madres solteras que trabajan; Guarderías
3 Más albercas y gimnasios públicos; Regulación de precios a partir del salario mínimo; Regulación de predios; Costo económico, rapidez y mayor cantidad de unidades de RTP y Cablebús; Limpieza de espacios específicos donde hay heces de animales; Retirar autos y poder estacionarse libremente, principalmente limpiar avenidas principales; Vigilancia y alumbrado en espacios obscuros; Más unidades para transporte de mujeres o de espacios para mujeres en el transporte público; Colocación de botones de pánico y que sirvan; Más semáforos, que sirvan y su mantenimiento, tener más oficiales de tránsito donde hay carencia de estos mismos; Aplicación de la ley correspondiente cuando hay eventos de violencia; Más construcción de vivienda y que se priorice a la población nativa y de escasos recursos; Para la vigilancia de las escuelas, se debería implementar capacitación y apoyo a voluntariado o personal encargado
4 Vigilancia y multas elevadas; adaptar lugares de vivienda para el adulto mayor; prioridad de los mayores en vivienda para localizarlos en planta baja; seguir el reglamento de construcción y adecuarlo para el adulto mayor; inclusión en la construcción de vivienda; multas fuertes a que nos tiran basura; labor social de limpieza comunitaria; regulación dónde sí y en donde no la vivienda privada; casas de ayuda; al verme con tratamiento médico; que realizan servicios comunitarios o alguna sanción; reubicar indigentes en lugares donde puedan vivir; más infraestructura accesible. Y aparte género: mayor seguridad; Género: botones de emergencia; cámara C5 que funcionen; Difusión; simplificación de trámites; mayor difusión y con tiempo para que la población se entere de los eventos; contar con un número para reportar y que se dé seguimiento; regular y prohibir cuetes
5 Renovar y pintar rampas y autos; Construir banquetas bien diseñadas con rampas; Colocar señalamientos de no estacionarse; Consulta de proyectos de vivienda; vivienda para la gente de la zona y analizar la población que llegará; Construcción de no más de 3 pisos; Beneficiar a los pobladores; Respuesta inmediata de la alcaldía, claridad en los trámites y su seguimiento; Más zonas de juego para hacer ejercicio
  espacio_publico_vivienda_movilidad_y_democracia_opiniones
1 NA
2 NA
3 NA
4 NA
5 NA
  seguridad_salud_mujeres_problematicas
1 Violencia de género en espacios públicos; escasez de campañas de salud; escasez de medicamentos; abandono de animales; Hay desinformación sobre la salud mental y no hay recursos y acceso; No hay educación sexual ni vacunas; Hay heces fecales, basura, estupefaciente y mascotas abandonadas; no hay botones de auxilio; no hay seguridad en las calles y hay un pésimo transporte público; Discriminación en diferentes sectores; Acoso en espacios públicos; Violencia hacia los hombres
2 El no abasto en medicamento; La contaminación afecta la salud de la población; Hay muchos puntos de comercio de droga (problemas en jóvenes); Apropiación del espacio público; Clínicas, más seguridad y prioridades; Clínicas de salud mental ya que es un problema invisible; Violencia de género; Inseguridad; Acoso; Violencia; Centros de apoyo a mujeres más cercanos
3 No funcionan los módulos, están abandonados; Hace falta medicamentos y estudios médicos; No hay suficientes elementos de seguridad para vigilar y mantener el orden; Hay problemas de salud por necesidades de animales; Hay problemas de salud por heces de animales; En seguridad en todos los servicios de salud / Servicio de salud ineficiente;  Sonideros entre (ruido alcohol drogas WC; Violencia de género; Inseguridad hacia la población Infante; Inseguridad hacia la población Infante; No hay cobertura de salud ah no derechohabientes
4 hay inseguridad; no hay luz; hay  extorsión a comercios; no hay seguimiento en los delitos; falta de ética por parte de los policías; corrupción por cuerpo policial; no hay apoyo de los policías; no hay ética; no hay botones de seguridad y cámara; no hay acceso a servicios públicos de salud; no se toma en cuenta a las personas con discapacidad; no hay apoyo para la salud mental; extorsión dentro del metro
5 Delincuencia; Adicciones; Enfermedades crónico degenerativas; Acoso de género; Gente armada; Corrupción de elementos policiacos; Personas en situación de calles o migrantes que son agresivas; Mala información por las autoridades; Hace falta centros de salud más grandes
  seguridad_salud_mujeres_posibles_soluciones
1 Mayor acceso a servicios públicos; Espacios exclusivos para hombres; Reforzar protocolos de seguridad para la mujeres; Programas de salud; adopción y campañas de esterilización, centros de salud animales; campañas NO abandono; campañas informativas y apoyo anticonceptivos; campañas concientización; reforzar los programas, hacer responsable al dueño; mantenimiento; mayor preparación de elementos para tener menos policías corruptos; aumento de autobuses que les brinden mantenimiento; Protocolo de seguridad; Líneas de apoyo psicológico integral; Que exista una línea de atención a hombres
2 Más centros médicos gratuitos; Campañas de concientización; Multas; Centros de apoyo para esa población regulados; Aplicaciones “Mi policía”, dispositivos de ayuda por una plataforma; Salud, más deporte y actividades para jóvenes; Más cerca de clínicas, más policías dedicados a su empleo y prioridad también a mujeres; Educación y difusión y uso de aplicaciones de seguridad
3 Activar los módulos de policía; Abastos; Patrullaje, más policías para cuidar a las mujeres; Limpia de los lugares; Mantenimiento de mobiliario; Cámaras del C5 que funcionen; Luminarias; Más botones de pánico, respuesta inmediata a solicitudes; Que las autoridades vigilen y regulen Sonideros; Más presupuesto de salud; Servicios gratuitos (Papanicolaou, estudios hormonales como ultrasonidos de mamas, radiografías); patrullaje, rondines las 24 horas 24 /7 y pie tierra; Cursos de talleres para concientizar a los jóvenes y padres; Obligar a escuelas para padres en escuelas públicas y privadas; Reeducar a los policías por medio de capacitaciones; Atención psicológica y legal (mujeres); Implementación de talleres en las escuelas para Defense saber cómo reaccionar ante eventos inseguros y de violencia; Más seguridad en las salidas de las escuelas; Mantenimiento en las alertas sísmicas; Más hospitales públicos para todos; Unificación del sistema de salud; Mejora del servicio médico; Equipamiento a hospital y mantenimiento de éste

In [176]:
talleres_raw <- talleres_raw %>%
clean_names() %>%
  
  # Pasar a formato largo
  
  pivot_longer(
    cols = c(
      medio_ambiente_agua_y_riesgos_problematicas,
      medio_ambiente_agua_y_riesgos_posibles_soluciones,
      medio_ambiente_agua_y_riesgos_opiniones,
      espacio_publico_vivienda_movilidad_y_democracia_problematicas,
      espacio_publico_vivienda_movilidad_y_democracia_posibles_soluciones,
      espacio_publico_vivienda_movilidad_y_democracia_opiniones,
      seguridad_salud_mujeres_problematicas,
      seguridad_salud_mujeres_posibles_soluciones,
      seguridad_salud_mujeres_opiniones,
      cultura_educacion_ciencia_economia_y_trabajo_problematicas,
      cultura_educacion_ciencia_economia_y_trabajo_posibles_soluciones,
      cultura_educacion_ciencia_economia_y_trabajo_opiniones
    ),
    names_to = "variable",
    values_to = "texto"
  ) %>%
  
  filter(!is.na(texto), texto != "") %>%
  
  separate_rows(texto, sep = ";") %>%
  
  mutate(texto = str_trim(texto)) %>%
  
  mutate(
    tipo = case_when(
      str_detect(variable, "problematicas") ~ "problematica",
      str_detect(variable, "posibles_soluciones") ~ "solucion",
      str_detect(variable, "opiniones") ~ "opinion"
    ),
    tema = case_when(
      str_detect(variable, "medio_ambiente") ~ "Medio ambiente, agua y riesgos",
      str_detect(variable, "espacio_publico") ~ "Espacio público, vivienda, movilidad y democracia",
      str_detect(variable, "seguridad_salud") ~ "Seguridad, salud, mujeres",
      str_detect(variable, "cultura_educacion") ~ "Cultura, educación, ciencia, economía y trabajo"
    )
  ) %>%
  
  select(-variable)

In [177]:
cat("Total de registros:", nrow(talleres_raw), "\n")

head(talleres_raw, 10)

Total de registros: 13899

   marca_temporal      direccion_de_correo_electronico
1  24/11/2025 12:01:11 paulinamorales3414@gmail.com
2  24/11/2025 12:01:11 paulinamorales3414@gmail.com
3  24/11/2025 12:01:11 paulinamorales3414@gmail.com
4  24/11/2025 12:01:11 paulinamorales3414@gmail.com
5  24/11/2025 12:01:11 paulinamorales3414@gmail.com
6  24/11/2025 12:01:11 paulinamorales3414@gmail.com
7  24/11/2025 12:01:11 paulinamorales3414@gmail.com
8  24/11/2025 12:01:11 paulinamorales3414@gmail.com
9  24/11/2025 12:01:11 paulinamorales3414@gmail.com
10 24/11/2025 12:01:11 paulinamorales3414@gmail.com
   lugar_programado_del_evento fecha_programada_del_evento
1  VIVERO NEZAHUALCÓYOTL       13/11/2025
2  VIVERO NEZAHUALCÓYOTL       13/11/2025
3  VIVERO NEZAHUALCÓYOTL       13/11/2025
4  VIVERO NEZAHUALCÓYOTL       13/11/2025
5  VIVERO NEZAHUALCÓYOTL       13/11/2025
6  VIVERO NEZAHUALCÓYOTL       13/11/2025
7  VIVERO NEZAHUALCÓYOTL       13/11/2025
8  VIVERO NEZAHUALCÓYOTL       13/11/2025
9  VIVERO NEZAHUALCÓYOTL       13/11/2025
10 VIVERO NEZAHUALCÓYOTL       13/11/2025
   hora_programada_de_inicio_del_evento
1  3:00:00 p.m.
2  3:00:00 p.m.
3  3:00:00 p.m.
4  3:00:00 p.m.
5  3:00:00 p.m.
6  3:00:00 p.m.
7  3:00:00 p.m.
8  3:00:00 p.m.
9  3:00:00 p.m.
10 3:00:00 p.m.
   tipo_de_evento                                 se_llevo_a_cabo_el_taller_7
1  1a sesión: "De los problemas a las propuestas" Sí
2  1a sesión: "De los problemas a las propuestas" Sí
3  1a sesión: "De los problemas a las propuestas" Sí
4  1a sesión: "De los problemas a las propuestas" Sí
5  1a sesión: "De los problemas a las propuestas" Sí
6  1a sesión: "De los problemas a las propuestas" Sí
7  1a sesión: "De los problemas a las propuestas" Sí
8  1a sesión: "De los problemas a las propuestas" Sí
9  1a sesión: "De los problemas a las propuestas" Sí
10 1a sesión: "De los problemas a las propuestas" Sí
   texto                                                         tipo
1  Escasez del agua, el agua está contaminada                    problematica
2  hay residuos tóxicos, basura                                  problematica
3  Hay pérdida de áreas verdes                                   problematica
4  hay colapso en el drenaje                                     problematica
5  existe sobrepoblación de animales callejeros                  problematica
6  Hay contaminación en canales, bosques y zonas de conservación problematica
7  urbanización (descentralización)                              problematica
8  Contaminación vehicular                                       problematica
9  Discriminación por preferencia sexual                         problematica
10 Acoso sexual                                                  problematica
   tema
1  Medio ambiente, agua y riesgos
2  Medio ambiente, agua y riesgos
3  Medio ambiente, agua y riesgos
4  Medio ambiente, agua y riesgos
5  Medio ambiente, agua y riesgos
6  Medio ambiente, agua y riesgos
7  Medio ambiente, agua y riesgos
8  Medio ambiente, agua y riesgos
9  Medio ambiente, agua y riesgos
10 Medio ambiente, agua y riesgos

In [178]:
# Stopwords 
stopwords <- c(
  "a","al","algo","algunas","algunos","ante","antes","como","con",
  "contra","cual","cuando","de","del","desde","donde","durante","e",
  "el","ella","ellas","ellos","en","entre","era","eran","eras",
  "eres","es","esa","esas","ese","eso","esos","esta","estaba","estaban",
  "estabas","estada","estadas","estado","estados","estamos",
  "estando","estar","estaremos","estará","estarán","estarás","estaré",
  "estaréis","estaría","estaríais","estaríamos","estarían","estarías",
  "estas","este","estemos","esto","estos","estoy","estuve","estuviera",
  "estuvierais","estuvieran","estuvieras","estuvieron","estuviese",
  "estuvieseis","estuviesen","estuvieses","estuvimos","estuviste",
  "estuvisteis","estuviéramos","estuviésemos","estuvo","está","estábamos",
  "estáis","están","estás","esté","estén","estés","fue","fuera",
  "fuerais","fueran","fueras","fueron","fuese","fueseis","fuesen","fueses",
  "fui","fuimos","fuiste","fuisteis","fuéramos","fuésemos","ha","habida",
  "habidas","habido","habidos","habiendo","habremos","habrá","habrán",
  "habrás","habré","habréis","habría","habríais","habríamos","habrían",
  "habrías","habéis","había","habíais","habíamos","habían","habías","han",
  "has","hasta","hay","haya","hayamos","hayan","hayas","hayáis","he",
  "hemos","hube","hubiera","hubierais","hubieran","hubieras","hubieron",
  "hubiese","hubieseis","hubiesen","hubieses","hubimos","hubiste",
  "hubisteis","hubiéramos","hubiésemos","hubo","la","las","le","les","lo",
  "los","me","mi","mis","mucho","muchos","muy","más","mí","mía","mías",
  "mío","míos","nada","ni","no","nos","nosotras","nosotros","nuestra",
  "nuestras","nuestro","nuestros","o","os","otra","otras","otro","otros",
  "para","pero","poco","por","porque","que","quien","quienes","qué","se",
  "sea","seamos","sean","seas","seáis","ser","seremos","será","serán",
  "serás","seré","seréis","sería","seríais","seríamos","serían","serías",
  "si","sido","siendo","sin","sobre","sois","somos","son","soy","su","sus",
  "suya","suyas","suyo","suyos","sí","también","tanto","te","tendremos",
  "tendrá","tendrán","tendrás","tendré","tendréis","tendría","tendríais",
  "tendríamos","tendrían","tendrías","tened","tenemos","tenga","tengamos",
  "tengan","tengas","tengo","tengáis","tenida","tenidas","tenido","tenidos",
  "teniendo","tenéis","tenía","teníais","teníamos","tenían","tenías","ti",
  "tiene","tienen","tienes","todo","todos","tu","tus","tuve","tuviera",
  "tuvierais","tuvieran","tuvieras","tuvieron","tuviese","tuvieseis",
  "tuviesen","tuvieses","tuvimos","tuviste","tuvisteis","tuviéramos",
  "tuviésemos","tuvo","tuya","tuyas","tuyo","tuyos","tú","un","una","uno",
  "unos","vosotras","vosotros","vuestra","vuestras","vuestro","vuestros",
  "y","ya","yo","él","éramos"
)

In [183]:

talleres_raw <- talleres_raw %>%
  mutate(
    texto = texto %>%
      stri_trans_general("Latin-ASCII") %>%   # quitar acentos
      str_to_lower() %>%                      # minúsculas
      str_replace_all("[[:punct:]]", "") %>%  # quitar puntuación
      str_squish() %>%                        # quitar espacios extra
      str_split("\\s+") %>%                   # separar palabras
      map(~ .x[!.x %in% stopwords]) %>%       # quitar stopwords
      map_chr(paste, collapse = " ")          # reconstruir texto
  ) %>%
  filter(!is.na(texto), texto != "")

head(talleres_raw, 5)

  marca_temporal      direccion_de_correo_electronico
1 24/11/2025 12:01:11 paulinamorales3414@gmail.com
2 24/11/2025 12:01:11 paulinamorales3414@gmail.com
3 24/11/2025 12:01:11 paulinamorales3414@gmail.com
4 24/11/2025 12:01:11 paulinamorales3414@gmail.com
5 24/11/2025 12:01:11 paulinamorales3414@gmail.com
  lugar_programado_del_evento fecha_programada_del_evento
1 VIVERO NEZAHUALCÓYOTL       13/11/2025
2 VIVERO NEZAHUALCÓYOTL       13/11/2025
3 VIVERO NEZAHUALCÓYOTL       13/11/2025
4 VIVERO NEZAHUALCÓYOTL       13/11/2025
5 VIVERO NEZAHUALCÓYOTL       13/11/2025
  hora_programada_de_inicio_del_evento
1 3:00:00 p.m.
2 3:00:00 p.m.
3 3:00:00 p.m.
4 3:00:00 p.m.
5 3:00:00 p.m.
  tipo_de_evento                                 se_llevo_a_cabo_el_taller_7
1 1a sesión: "De los problemas a las propuestas" Sí
2 1a sesión: "De los problemas a las propuestas" Sí
3 1a sesión: "De los problemas a las propuestas" Sí
4 1a sesión: "De los problemas a las propuestas" Sí
5 1a sesión: "De los problemas a las propuestas" Sí
  texto                                     tipo
1 escasez agua agua contaminada             problematica
2 residuos toxicos basura                   problematica
3 perdida areas verdes                      problematica
4 colapso drenaje                           problematica
5 existe sobrepoblacion animales callejeros problematica
  tema
1 Medio ambiente, agua y riesgos
2 Medio ambiente, agua y riesgos
3 Medio ambiente, agua y riesgos
4 Medio ambiente, agua y riesgos
5 Medio ambiente, agua y riesgos

In [185]:
write_xlsx(talleres_raw, "talleres_limpios.xlsx")
browseURL(getwd())